
const PRODUCTS=[{"name": "7-Drawer Rolling Tool Chest", "category": "Tool Storage", "price": 499.99, "img": "assets/products/7-drawer-tool-chest.webp", "desc": "A heavy-duty rolling chest with organized drawers for everyday workshop tools."}, {"name": "Heavy-Duty Workbench", "category": "Workstations", "price": 349.99, "img": "assets/products/heavy-duty-workbench.webp", "desc": "A solid steel-frame bench with a durable wood work surface for demanding projects."}, {"name": "Wall Pegboard Set", "category": "Wall Organization", "price": 89.99, "img": "assets/products/wall-pegboard-set.webp", "desc": "A modular pegboard system for keeping hand tools visible and within reach."}, {"name": "Modular Storage Cabinet", "category": "Storage", "price": 349.99, "img": "assets/products/modular-storage-cabinet.webp", "desc": "Lockable vertical storage for tools, supplies and workshop equipment."}, {"name": "20V Cordless Drill Kit", "category": "Power Tools", "price": 129.99, "img": "assets/products/cordless-drill-kit.webp", "desc": "A compact cordless drill kit for repairs, builds and everyday workshop work."}, {"name": "Rolling Tool Cart", "category": "Mobile Storage", "price": 299.99, "img": "assets/products/rolling-tool-cart.webp", "desc": "A compact mobile cart that keeps frequently used tools close to the bench."}, {"name": "7-Drawer Tool Chest", "category": "Tool Storage", "price": 459.99, "img": "assets/products/7-drawer-tool-chest.webp", "desc": "A compact seven-drawer chest for organized bench-side storage."}, {"name": "Pro Workbench", "category": "Workstations", "price": 599.99, "img": "assets/products/heavy-duty-workbench-pro.webp", "desc": "A professional work surface designed for assembly, repair and fabrication."}, {"name": "5-Tier Storage Rack", "category": "Shelving", "price": 199.99, "img": "assets/products/5-tier-storage-rack.webp", "desc": "Open five-tier shelving for bins, cases, parts and workshop supplies."}, {"name": "Wall Organizer Kit", "category": "Wall Organization", "price": 99.99, "img": "assets/products/wall-organizer-kit.webp", "desc": "Hooks, holders and small bins arranged into one flexible wall system."}, {"name": "20V Cordless Drill", "category": "Power Tools", "price": 119.99, "img": "assets/products/20v-cordless-drill.webp", "desc": "A versatile 20V drill for home projects and workshop builds."}, {"name": "Portable Tool Box", "category": "Tool Storage", "price": 59.99, "img": "assets/products/portable-tool-box.webp", "desc": "A compact hard-shell case for portable tools, bits and project essentials."}];
function money(n){return '$'+n.toFixed(2)}
function getCart(){try{return JSON.parse(localStorage.getItem('bench-cart')||'[]')}catch(e){return[]}}
function saveCart(c){localStorage.setItem('bench-cart',JSON.stringify(c)); updateCartCount()}
function addToCart(i){const c=getCart();c.push(PRODUCTS[i]);saveCart(c);toast('Added to your bench.')} 
function removeCart(i){const c=getCart();c.splice(i,1);saveCart(c);renderCart()}
function updateCartCount(){document.querySelectorAll('[data-cart-count]').forEach(e=>e.textContent=getCart().length)}
function toast(msg){let t=document.querySelector('.toast');if(!t){t=document.createElement('div');t.className='toast';document.body.appendChild(t)}t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),1700)}
function productCard(p,i){return `<article class="card"><a class="card-media" href="product.html?id=${i}"><img src="${p.img}" alt="${p.name}" loading="lazy"></a><div class="card-body"><div class="kicker">${p.category}</div><h3><a href="product.html?id=${i}">${p.name}</a></h3><div class="desc">${p.desc}</div><div class="price">${money(p.price)}</div><div class="card-actions"><button class="heart" onclick="toggleSave(${i})" aria-label="Save">♡</button><button class="btn" onclick="addToCart(${i})">Add to bench</button></div></div></article>`}
function renderProducts(list=PRODUCTS,target='product-grid'){const el=document.getElementById(target);if(el)el.innerHTML=list.map((p,i)=>productCard(p,i)).join('');updateCartCount()}
function toggleSave(i){let s=JSON.parse(localStorage.getItem('bench-saved')||'[]');if(!s.includes(i))s.push(i);else s=s.filter(x=>x!==i);localStorage.setItem('bench-saved',JSON.stringify(s));toast('Saved products updated')}
function initFilters(){const search=document.getElementById('search');const buttons=document.querySelectorAll('[data-filter]');let active='All';function go(){let q=(search?.value||'').toLowerCase();let arr=PRODUCTS.filter(p=>(active==='All'||p.category===active)&&(!q||(`${p.name} ${p.category} ${p.desc}`).toLowerCase().includes(q)));renderProducts(arr)}buttons.forEach(b=>b.addEventListener('click',()=>{buttons.forEach(x=>x.classList.remove('active'));b.classList.add('active');active=b.dataset.filter;go()}));search?.addEventListener('input',go);go()}
function renderProduct(){const id=Number(new URLSearchParams(location.search).get('id')||0),p=PRODUCTS[id]||PRODUCTS[0];const el=document.getElementById('product-detail');if(!el)return;el.innerHTML=`<div class="product-page"><div class="product-large"><img src="${p.img}" alt="${p.name}"></div><div class="product-info"><div class="kicker">${p.category}</div><h1>${p.name}</h1><div class="price">${money(p.price)}</div><p>${p.desc}</p><ul class="specs"><li>Workshop-focused construction</li><li>Designed for practical organization</li><li>Clean, modular footprint</li><li>Built for everyday project use</li></ul><div class="qty"><input id="qty" type="number" min="1" value="1"><button class="btn" onclick="addMany(${id})">Add to bench</button></div></div></div>`}
function addMany(i){let q=Math.max(1,Number(document.getElementById('qty')?.value||1));const c=getCart();for(let n=0;n<q;n++)c.push(PRODUCTS[i]);saveCart(c);toast(q+' item(s) added to your bench')}
function renderCart(){const el=document.getElementById('cart-items');if(!el)return;const c=getCart();if(!c.length){el.innerHTML='<div class="empty"><h2>Your bench is empty.</h2><p>Add storage, workstations or tools to build your workshop setup.</p><a class="btn" href="shop.html">Browse products</a></div>';return}el.innerHTML=c.map((p,i)=>`<div style="display:flex;gap:16px;align-items:center;background:#fff;border:1px solid #ddd;padding:14px;border-radius:14px;margin-bottom:10px"><img src="${p.img}" style="width:110px;height:85px;object-fit:contain;background:#f7f6f2;border-radius:10px"><div style="flex:1"><b>${p.name}</b><div>${money(p.price)}</div></div><button class="filter" onclick="removeCart(${i})">Remove</button></div>`).join('');document.getElementById('cart-total').textContent=money(c.reduce((a,p)=>a+p.price,0));updateCartCount()}
document.addEventListener('DOMContentLoaded',()=>{updateCartCount();renderProduct();renderCart();if(document.getElementById('product-grid')){if(document.body.dataset.filterpage)initFilters();else renderProducts()}});

document.addEventListener('DOMContentLoaded',()=>{
 const cat=document.body.dataset.category;
 const grid=document.getElementById('product-grid');
 if(cat && grid){
   const arr=PRODUCTS.filter(p=>p.category===cat);
   renderProducts(arr);
 }
});
